name: AlertCoreApp

options:
  bundleIdPrefix: com.alertcore
  deploymentTarget:
    iOS: 16.0

settings:
  base:
    SWIFT_VERSION: 5.0

packages:
  CocoaMQTT:
    url: https://github.com/emqx/CocoaMQTT.git
    from: 2.1.6

targets:
  AlertCoreApp:
    type: application
    platform: iOS
    sources:
      - path: AlertCoreApp
    resources:
      - path: AlertCoreApp/Resources/AlertCoreTone.wav
    dependencies:
      - package: CocoaMQTT
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.alertcore.mobile
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: AlertCoreApp/Resources/Info.plist
    scheme:
      testTargets: []
      gatherCoverageData: false